[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge"]
name = "rcghpge.github.io"
platforms = ["linux-64"]
version = "0.1.4"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"
nodejs = ">=26.8.1,<26.9"
vim = ">=9.2.785,<10"
texinfo = ">=7.2,<8"
tldr = ">=3.4.4,<4"
qtsass = ">=0.4.0,<0.5"
nano = ">=9.2,<10"
emacs = ">=31.1,<32"

[pypi-dependencies]
npm = ">=0.1.1, <0.2"
clamd = ">=1.0.2, <2"
